// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARiVFpXDiXy_6W7l3UtEkCPNr0_A6_TWk',
    appId: '1:201686143127:android:4630d364c4cfbaa41c59d2',
    messagingSenderId: '201686143127',
    projectId: 'emart-fc547',
    databaseURL: 'https://emart-fc547-default-rtdb.firebaseio.com',
    storageBucket: 'emart-fc547.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt4xW8uvrG388ybuHWzC81AgmKKw3MlP0',
    appId: '1:201686143127:ios:6b895af5309302071c59d2',
    messagingSenderId: '201686143127',
    projectId: 'emart-fc547',
    databaseURL: 'https://emart-fc547-default-rtdb.firebaseio.com',
    storageBucket: 'emart-fc547.firebasestorage.app',
    androidClientId: '201686143127-26k2cmhd0kql8h5bufcmck056u2bt5vh.apps.googleusercontent.com',
    iosClientId: '201686143127-l3dmqc7v1v8l3qcrkf0l2uvron4lm9ai.apps.googleusercontent.com',
    iosBundleId: 'emart.app.customer',
  );
}
